# Generated by Django 5.2.9 on 2025-12-30 23:18

import apps.pet.models
import django.db.models.deletion
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, default='', max_length=128, verbose_name='Street')),
                ('building_number', models.CharField(blank=True, default='', max_length=16, verbose_name='Building No.')),
                ('postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Postal Code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Lat')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Lng')),
                ('location', models.JSONField(blank=True, default=dict, null=True)),
                ('city', smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.PROTECT, to='pet.city', verbose_name='City')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pet.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['country', 'region', 'city', 'street'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Pet Name')),
                ('species', models.CharField(max_length=40, verbose_name='Species')),
                ('breed', models.CharField(blank=True, default='', max_length=80, verbose_name='Breed')),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10, verbose_name='Sex')),
                ('age_years', models.PositiveIntegerField(default=0, verbose_name='Age (years)')),
                ('age_months', models.PositiveIntegerField(default=0, verbose_name='Age (months)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('dewormed', models.BooleanField(default=False, verbose_name='Dewormed')),
                ('vaccinated', models.BooleanField(default=False, verbose_name='Vaccinated')),
                ('microchipped', models.BooleanField(default=False, verbose_name='Microchipped')),
                ('sterilized', models.BooleanField(default=False, verbose_name='Sterilized/Neutered')),
                ('child_friendly', models.BooleanField(default=False, verbose_name='Child Friendly')),
                ('trained', models.BooleanField(default=False, verbose_name='House Trained')),
                ('loves_play', models.BooleanField(default=False, verbose_name='Loves to Play')),
                ('loves_walks', models.BooleanField(default=False, verbose_name='Loves Walks')),
                ('good_with_dogs', models.BooleanField(default=False, verbose_name='Good with Dogs')),
                ('good_with_cats', models.BooleanField(default=False, verbose_name='Good with Cats')),
                ('affectionate', models.BooleanField(default=False, verbose_name='Affectionate')),
                ('needs_attention', models.BooleanField(default=False, verbose_name='Needs Attention')),
                ('is_stray', models.BooleanField(default=False, verbose_name='Found as Stray')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Contact Phone')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], db_index=True, default='submitted', max_length=20, verbose_name='Status')),
                ('review_note', models.CharField(blank=True, default='', max_length=200, verbose_name='Review Note')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='pet.address', verbose_name='Address')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_donor', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='DonationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='donations/')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pet.donation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Pet Name')),
                ('species', models.CharField(max_length=40, verbose_name='Species')),
                ('breed', models.CharField(blank=True, default='', max_length=80, verbose_name='Breed')),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10, verbose_name='Sex')),
                ('age_years', models.PositiveIntegerField(default=0, verbose_name='Age (years)')),
                ('age_months', models.PositiveIntegerField(default=0, verbose_name='Age (months)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('dewormed', models.BooleanField(default=False, verbose_name='Dewormed')),
                ('vaccinated', models.BooleanField(default=False, verbose_name='Vaccinated')),
                ('microchipped', models.BooleanField(default=False, verbose_name='Microchipped')),
                ('child_friendly', models.BooleanField(default=False, verbose_name='Child Friendly')),
                ('trained', models.BooleanField(default=False, verbose_name='House Trained')),
                ('loves_play', models.BooleanField(default=False, verbose_name='Loves to Play')),
                ('loves_walks', models.BooleanField(default=False, verbose_name='Loves Walks')),
                ('good_with_dogs', models.BooleanField(default=False, verbose_name='Good with Dogs')),
                ('good_with_cats', models.BooleanField(default=False, verbose_name='Good with Cats')),
                ('affectionate', models.BooleanField(default=False, verbose_name='Affectionate')),
                ('needs_attention', models.BooleanField(default=False, verbose_name='Needs Attention')),
                ('sterilized', models.BooleanField(default=False, verbose_name='Sterilized/Neutered')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Contact Phone')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='Cover')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('available', 'Available'), ('pending', 'Pending'), ('adopted', 'Adopted'), ('archived', 'Archived'), ('lost', 'Lost')], db_index=True, default='available', max_length=20, verbose_name='Status')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='pet.address', verbose_name='Address')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(blank=True, default='', max_length=80, verbose_name='Pet Name')),
                ('species', models.CharField(help_text='cat/dog/…', max_length=50)),
                ('breed', models.CharField(blank=True, default='', max_length=100)),
                ('color', models.CharField(blank=True, default='', max_length=100)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10, verbose_name='Sex')),
                ('size', models.CharField(blank=True, default='', max_length=20)),
                ('lost_time', models.DateTimeField(help_text='Lost time (local)')),
                ('description', models.TextField(blank=True, default='')),
                ('reward', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.pet.models.lost_upload_to)),
                ('status', models.CharField(choices=[('open', 'Open'), ('found', 'Found'), ('closed', 'Closed')], default='open', max_length=20)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='losts', to='pet.address', verbose_name='Address')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lost_reports', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_reports', to='pet.pet')),
            ],
            options={
                'verbose_name': 'Lost',
                'verbose_name_plural': 'Losts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='created_pet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_donor', to='pet.pet'),
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='', verbose_name='Message to Owner')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], db_index=True, default='submitted', max_length=20, verbose_name='Status')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_adoption', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='pet.pet')),
            ],
            options={
                'verbose_name': 'Adoption',
                'verbose_name_plural': 'Adoptions',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='PetFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='pet.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pet Favorite',
                'verbose_name_plural': 'Pet Favorites',
            },
        ),
        migrations.CreateModel(
            name='PetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pets/photos/', verbose_name='Photo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pet.pet', verbose_name='Pet')),
            ],
            options={
                'verbose_name': 'Pet Photo',
                'verbose_name_plural': 'Pet Photos',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=64)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='pet.country')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='pet.region'),
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.PROTECT, to='pet.region', verbose_name='Region'),
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Shelter Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Phone')),
                ('website', models.URLField(blank=True, default='', verbose_name='Website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shelters/logos/', verbose_name='Logo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='shelters/covers/', verbose_name='Cover Image')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Maximum number of animals', verbose_name='Capacity')),
                ('current_animals', models.PositiveIntegerField(default=0, verbose_name='Current Animals')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Founded Year')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by admin', verbose_name='Verified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('facebook_url', models.URLField(blank=True, default='', verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, default='', verbose_name='Instagram')),
                ('twitter_url', models.URLField(blank=True, default='', verbose_name='Twitter/X')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelters', to='pet.address', verbose_name='Address')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shelters', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Shelter',
                'verbose_name_plural': 'Shelters',
                'ordering': ['-is_verified', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['status'], name='pet_pet_status_d405f9_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['species', 'breed'], name='pet_pet_species_aeab59_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['created_by'], name='pet_pet_created_66a81e_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status'], name='pet_donatio_status_533559_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor'], name='pet_donatio_donor_i_9c757c_idx'),
        ),
        migrations.AddIndex(
            model_name='adoption',
            index=models.Index(fields=['pet', 'status'], name='pet_adoptio_pet_id_3c28ca_idx'),
        ),
        migrations.AddIndex(
            model_name='adoption',
            index=models.Index(fields=['applicant', 'status'], name='pet_adoptio_applica_ca5b73_idx'),
        ),
        migrations.AddIndex(
            model_name='petfavorite',
            index=models.Index(fields=['user', 'pet'], name='pet_petfavo_user_id_cbfb3c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='petfavorite',
            unique_together={('user', 'pet')},
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['country', 'name'], name='pet_region_country_384b1b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('country', 'name')},
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['region', 'name'], name='pet_city_region__73d7cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('region', 'name')},
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['country', 'region', 'city'], name='pet_address_country_8537a3_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['postal_code'], name='pet_address_postal__555dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='shelter',
            index=models.Index(fields=['is_active', 'is_verified'], name='pet_shelter_is_acti_7f7b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='shelter',
            index=models.Index(fields=['name'], name='pet_shelter_name_0e4218_idx'),
        ),
    ]
