# Generated by Django 5.2.9 on 2026-01-18 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0002_donation_shelter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiry"),
                            ("pet_health", "Pet Health"),
                            ("adoption", "Adoption Issue"),
                            ("lost_found", "Lost/Found Pet"),
                            ("shelter", "Shelter Issue"),
                            ("technical", "Technical Issue"),
                            ("feedback", "Feedback"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("closed", "Closed"),
                            ("resolved", "Resolved"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="Phone"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved At"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin assigned to this ticket",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="pet_ticket_status_38f6ec_idx",
                    ),
                    models.Index(
                        fields=["priority", "-created_at"],
                        name="pet_ticket_priorit_82ea4b_idx",
                    ),
                    models.Index(
                        fields=["category"], name="pet_ticket_categor_172ba0_idx"
                    ),
                    models.Index(
                        fields=["created_by"], name="pet_ticket_created_14b6cd_idx"
                    ),
                    models.Index(
                        fields=["assigned_to"], name="pet_ticket_assigne_6d8fba_idx"
                    ),
                ],
            },
        ),
    ]
