# Generated by Django 5.2.9 on 2026-01-18 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0003_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="shelter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pets",
                to="pet.shelter",
                verbose_name="Shelter",
            ),
        ),
    ]
