# Generated by Django 5.2.9 on 2026-01-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_pet_shelter'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='sex',
            field=models.CharField(choices=[('male', 'Boy'), ('female', 'Girl')], default='male', max_length=10, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='sex',
            field=models.CharField(choices=[('male', 'Boy'), ('female', 'Girl')], default='male', max_length=10, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('male', 'Boy'), ('female', 'Girl')], default='male', max_length=10, verbose_name='Sex'),
        ),
    ]
