# Generated by Django 5.2.9 on 2026-01-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_pet_size_alter_donation_sex_alter_lost_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Description'),
        ),
    ]
