# Generated by Django 5.2.9 on 2026-01-25 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_alter_pet_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('pet_count', models.PositiveIntegerField(default=0, verbose_name='Number of Current Pets')),
                ('pet_types', models.CharField(help_text='e.g., 2 dogs, 1 cat', max_length=255, verbose_name='Types of Pets')),
                ('motivation', models.TextField(verbose_name='Why do you want to be a Holiday Family?')),
                ('terms_agreed', models.BooleanField(default=False, verbose_name='Terms and Conditions Agreed')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Application Status')),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Applied At')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('review_notes', models.TextField(blank=True, verbose_name='Review Notes')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holiday_family_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_family_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Holiday Family',
                'verbose_name_plural': 'Holiday Families',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['status', '-applied_at'], name='pet_holiday_status_2d0d42_idx'), models.Index(fields=['user'], name='pet_holiday_user_id_9c1c79_idx')],
            },
        ),
    ]
