# Generated by Django 5.2.9 on 2026-01-25 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayFamilyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('pet_count', models.IntegerField()),
                ('can_take_dogs', models.BooleanField(default=False)),
                ('can_take_cats', models.BooleanField(default=False)),
                ('can_take_rabbits', models.BooleanField(default=False)),
                ('can_take_others', models.CharField(blank=True, max_length=255)),
                ('motivation', models.TextField()),
                ('introduction', models.TextField()),
                ('id_document', models.FileField(upload_to='holiday_family/id_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('family_photos', models.FileField(upload_to='holiday_family/family_photos/')),
                ('terms_agreed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
