# Generated by Django 5.2.9 on 2026-01-25 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_family', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidayfamilyapplication',
            name='family_photos',
        ),
        migrations.CreateModel(
            name='HolidayFamilyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='holiday_family/family_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_photos', to='holiday_family.holidayfamilyapplication')),
            ],
        ),
    ]
