# Generated by Django 5.2.9 on 2026-01-25 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_family', '0002_remove_holidayfamilyapplication_family_photos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayfamilyapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holiday_family_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
