# Generated by Django 5.2.9 on 2026-01-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_family', '0003_holidayfamilyapplication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayfamilyapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='拒绝的原因', null=True),
        ),
    ]
