# Generated by Django 5.2.9 on 2025-12-30 23:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message='Phone format incorrect（e.g.：+48 123-456-789 or 13800138000）', regex='^\\+?[0-9\\- ]{6,20}$')])),
                ('avatar', models.ImageField(blank=True, help_text='User avatar image', null=True, upload_to='avatars/%Y/%m/%d/')),
                ('preferred_species', models.CharField(blank=True, help_text='偏好的物种（如：dog, cat）', max_length=50)),
                ('preferred_size', models.CharField(blank=True, help_text='偏好的大小（如：small, medium, large）', max_length=50)),
                ('preferred_age_min', models.IntegerField(blank=True, help_text='偏好的最小年龄（月）', null=True)),
                ('preferred_age_max', models.IntegerField(blank=True, help_text='偏好的最大年龄（月）', null=True)),
                ('preferred_gender', models.CharField(blank=True, help_text='偏好的性别（male/female）', max_length=20)),
                ('has_experience', models.BooleanField(default=False, help_text='是否有养宠经验')),
                ('living_situation', models.CharField(blank=True, help_text='居住环境（如：apartment, house）', max_length=100)),
                ('has_yard', models.BooleanField(default=False, help_text='是否有院子')),
                ('other_pets', models.CharField(blank=True, help_text='家中其他宠物', max_length=200)),
                ('additional_notes', models.TextField(blank=True, help_text='其他偏好说明')),
                ('prefer_vaccinated', models.BooleanField(default=False, help_text='偏好已接种疫苗的宠物')),
                ('prefer_sterilized', models.BooleanField(default=False, help_text='偏好已绝育的宠物')),
                ('prefer_dewormed', models.BooleanField(default=False, help_text='偏好已驱虫的宠物')),
                ('prefer_child_friendly', models.BooleanField(default=False, help_text='偏好适合儿童的宠物')),
                ('prefer_trained', models.BooleanField(default=False, help_text='偏好已训练的宠物')),
                ('prefer_loves_play', models.BooleanField(default=False, help_text='偏好喜欢玩耍的宠物')),
                ('prefer_loves_walks', models.BooleanField(default=False, help_text='偏好喜欢散步的宠物')),
                ('prefer_good_with_dogs', models.BooleanField(default=False, help_text='偏好与其他狗相处友善的宠物')),
                ('prefer_good_with_cats', models.BooleanField(default=False, help_text='偏好与猫相处友善的宠物')),
                ('prefer_affectionate', models.BooleanField(default=False, help_text='偏好富有感情的宠物')),
                ('prefer_needs_attention', models.BooleanField(default=False, help_text='偏好需要陪伴的宠物')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待接受'), ('accepted', '已接受'), ('blocked', '已拒绝')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_initiated', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Friendship',
                'verbose_name_plural': 'Friendships',
                'indexes': [models.Index(fields=['from_user', 'status'], name='user_friend_from_us_7edf18_idx'), models.Index(fields=['to_user', 'status'], name='user_friend_to_user_d463c9_idx')],
                'unique_together': {('from_user', 'to_user')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('reply', '有人回复了我的评论'), ('mention', '有人提到了我'), ('system', '系统通知')], default='reply', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.comment')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_notifi_user_id_7c7879_idx'), models.Index(fields=['user', 'is_read'], name='user_notifi_user_id_c3061c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Private Message',
                'verbose_name_plural': 'Private Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'recipient', '-created_at'], name='user_privat_sender__8f2179_idx'), models.Index(fields=['recipient', 'is_read'], name='user_privat_recipie_3eb669_idx')],
            },
        ),
        migrations.CreateModel(
            name='ViewStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'View statistics',
                'verbose_name_plural': 'View statistics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'date'], name='user_views_content_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'date'), name='user_views_content_type_idx')],
            },
        ),
    ]
