# Generated by Django 5.2.9 on 2026-01-01 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="friendship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="user.friendship",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("reply", "有人回复了我的评论"),
                    ("mention", "有人提到了我"),
                    ("friend_request", "好友申请"),
                    ("system", "系统通知"),
                ],
                default="reply",
                max_length=20,
            ),
        ),
    ]
