# Generated by Django 5.2.9 on 2026-01-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_notification_friendship_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatemessage",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
    ]
