# Generated by Django 5.2.9 on 2026-01-25 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_family', '0002_remove_holidayfamilyapplication_family_photos_and_more'),
        ('user', '0003_privatemessage_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='holiday_family_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='holiday_family.holidayfamilyapplication'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reply', '有人回复了我的评论'), ('mention', '有人提到了我'), ('friend_request', '好友申请'), ('system', '系统通知'), ('holiday_family_apply', 'Holiday Family 申请')], default='reply', max_length=20),
        ),
    ]
