# Generated by Django 5.2.9 on 2026-01-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_notification_holiday_family_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reply', '有人回复了我的评论'), ('mention', '有人提到了我'), ('friend_request', '好友申请'), ('system', '系统通知'), ('holiday_family_apply', 'Holiday Family 申请'), ('holiday_family_approve', 'Holiday Family 申请已批准'), ('holiday_family_reject', 'Holiday Family 申请已拒绝')], default='reply', max_length=30),
        ),
    ]
