# Generated by Django 5.2.9 on 2026-01-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_holiday_family_certified",
            field=models.BooleanField(
                default=False, help_text="用户是否通过了Holiday Family认证"
            ),
        ),
    ]
